#! /bin/sh

# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Handle NVIDIA Tegra Cpu Auto-hotplug
if [ -w /sys/module/cpu_tegra3/parameters/auto_hotplug ]; then
    echo $CONTROL_NV_CPU_AUTO_HOTPLUG > /sys/module/cpu_tegra3/parameters/auto_hotplug
    if [ x$CONTROL_NV_CPU_AUTO_HOTPLUG = x1 ]; then
        log "VERBOSE" "NVIDIA tegra auto-hotplug enabled."
    else
        log "VERBOSE" "NVIDIA tegra auto-hotplug disabled."
    fi
else
        log "VERBOSE" "NVIDIA tegra auto-hotplug is not available on this system."
fi
